### PR TITLE
fix: handle no input case gracefully

### PR DESCRIPTION
**Pull request by TylerGillson**
## Related GitHub Issues
N/A

## Problem

I have an action that uses either secrets or inputs and the hide sensitive info action fails when using secrets.

## Solution

Handle case where inputs are undefined.

## Testing

- [ ] Added automated tests. 
- [X] Manually tested. If you check this box, provide instructions for others to test, too.

### CODE REVIEW

**Comment by levibostian** [comment]
Thank you so much for opening this PR! 

The code change looks good so far. Before merging, could you explain what the expected and actual behavior of the action is for your use case?

**Comment by levibostian** [comment]
Also, there is a [github actions workflow](https://github.com/levibostian/action-hide-sensitive-inputs/blob/main/.github/workflows/test.yml) (that calls [this workflow](https://github.com/levibostian/action-hide-sensitive-inputs/blob/main/.github/workflows/run-action-via-dispatch.yml)) that runs the action each time a push happens. This is used for testing. It's a manual process where you need to manually read the output of the action to see if it has the expected behavior. 

Could you make sure that your use case is being considered in this test? If not, modify the action to add your use case and then show the action run in this PR to confirm the test passes.

**Comment by TylerGillson** [comment]
@levibostian I released from my fork to verify:
image

I took a look at your test action and it would not be compatible with testing this use case. I'd need to add an entirely separate test action with no defaults. To be completely honest, my appetite for doing that for such a trivial fix is low. Especially when I know it works.

**Comment by TylerGillson** [comment]
Expected and actual behaviour is for the action to be a no-op when no inputs were provided.

**Comment by levibostian** [comment]
That's all fair. 

I appreciate the contribution! Thanks for opening a PR!

**Comment by TylerGillson** [comment]
Thanks @levibostian! I'll delete my release 😄

**Pull request merged**
